// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZNWzLca0p30aKFidkc30_hrE7My7Rrfs',
    appId: '1:688021011828:web:10426a0f605e83f1dc4021',
    messagingSenderId: '688021011828',
    projectId: 'medicinepharm-d6265',
    authDomain: 'medicinepharm-d6265.firebaseapp.com',
    storageBucket: 'medicinepharm-d6265.firebasestorage.app',
    measurementId: 'G-B6N7G3J3Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjR2d2qL2JMvr8Mu3Z3pPiVANCDPH_pHo',
    appId: '1:688021011828:android:31e056968716318bdc4021',
    messagingSenderId: '688021011828',
    projectId: 'medicinepharm-d6265',
    storageBucket: 'medicinepharm-d6265.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqWgHVU8SMi9pthvP13EUjwMzmFPNb8WI',
    appId: '1:688021011828:ios:f8c7978dff3f3045dc4021',
    messagingSenderId: '688021011828',
    projectId: 'medicinepharm-d6265',
    storageBucket: 'medicinepharm-d6265.firebasestorage.app',
    iosBundleId: 'com.example.medpharm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqWgHVU8SMi9pthvP13EUjwMzmFPNb8WI',
    appId: '1:688021011828:ios:f8c7978dff3f3045dc4021',
    messagingSenderId: '688021011828',
    projectId: 'medicinepharm-d6265',
    storageBucket: 'medicinepharm-d6265.firebasestorage.app',
    iosBundleId: 'com.example.medpharm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZNWzLca0p30aKFidkc30_hrE7My7Rrfs',
    appId: '1:688021011828:web:04cf1a05ddaf1003dc4021',
    messagingSenderId: '688021011828',
    projectId: 'medicinepharm-d6265',
    authDomain: 'medicinepharm-d6265.firebaseapp.com',
    storageBucket: 'medicinepharm-d6265.firebasestorage.app',
    measurementId: 'G-XBVMLB7782',
  );
}
